map_data:
  use_sim_time : True
  map_frame : 'map'
  radiation_sensor_frame : 'radiation_sensor_link'
  map_update_rate : 5.0

  # map size
  map_width: 19.0           # x축
  map_height: 20.0          # y축
  map_origin_x: -9.5
  map_origin_y: -10.0

  map_resolution: 0.2 # 0.2 # 0.05
  max_intensity: 150.0 # 150.0
